[project]
name = "chai"
version = "0.1.0"
description = "Chat with AI in the terminal"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "anthropic>=0.49.0",
    "google-genai>=1.5.0",
    "openai>=1.65.5",
    "rich>=13.9.4",
]
